<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="mrolap03" failures="1" tests="4" name="Test.TestKeywords" time="0.034" errors="0" timestamp="2024-10-17T14:37:56 IST" skipped="2">
  <testcase classname="Test.TestKeywords" name="test_B" time="0.029">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Test.TestKeywords.test_B(TestKeywords.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- test_B -->
  <system-out/>
  <testcase classname="Test.TestKeywords" name="test_A" time="0.002">
    <skipped/>
  </testcase> <!-- test_A -->
  <system-out/>
  <testcase classname="Test.TestKeywords" name="test_C" time="0.003"/>
  <system-out/>
  <testcase classname="Test.TestKeywords" name="test_D">
    <skipped/>
  </testcase> <!-- test_D -->
  <system-out/>
</testsuite> <!-- Test.TestKeywords -->
